server:
  port: 8082
  use-forward-headers: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/inventory
    username: test
    password: passwd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9103/uaa/token_keys
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/